/*
 *	parse.h			parser header file
 *
 *	Copyright © 1996 Jarno Seppänen; see 3MU.c for licensing info.
 */

#ifndef	PARSE_H
#define	PARSE_H 1

/* lähdekoodissa käytettävät merkit: */

#define	CHAR_COMMENT	'!'
#define CHAR_SEQBEG		'{'
#define CHAR_SEQEND		'}'
#define CHAR_TAGEND		'='
#define CHAR_QUOTE		'"'
#define	CHAR_LF			'\n'
#define	CHAR_TAB		'\t'
#define CHAR_SPC		' '
#define CHAR_NUL		0


#endif	/* PARSE_H */
