//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by wdrum.rc
//
#define IDI_ICON1                       106
#define ID_BPM_110                      110
#define IDC_SLIDER1                     1000
#define IDC_SLIDER2                     1001
#define IDC_VCO_SQUARE                  1005
#define IDC_VCO_TRIANG                  1006
#define IDC_VCO_FILE                    1007
#define IDC_EDIT1                       1008
#define IDC_EG_A                        1009
#define IDC_EG_S                        1010
#define IDC_EG_D                        1011
#define IDC_EG_R                        1012
#define ID_EG_VCF_MOD                   1013
#define ID_EG_VCO_MOD                   1014
#define ID_EG_VCA_MOD                   1015
#define IDC_VCF_CUTOFF                  1016
#define IDC_VCF_RESONANCE               1017
#define IDC_VCO_PULSEWIDTH              1018
#define IDC_VCF_CUTOFFFACT              1019
#define IDC_EG_ADSRFACT                 1020
#define IDC_VCF_RESOFACT                1021
#define IDC_VCO_GAIN                    1022
#define IDC_VCO_DETUNE                  1023
#define IDC_STATIC1                     1024
#define IDC_VCF_AMOUNT                  1025
#define IDC_EDIT2                       1026
#define IDC_CHECK1                      1027
#define IDC_CHECK2                      1028
#define IDC_CHECK3                      1029
#define IDC_CHECK4                      1030
#define IDC_CHECK5                      1031
#define IDC_CHECK6                      1032
#define IDC_CHECK7                      1033
#define IDC_CHECK8                      1034
#define IDC_CHECK9                      1035
#define IDC_BUTTON1                     1036
#define ID_FILES_LOAD                   40001
#define ID_FILES_SAVE                   40002
#define ID_FILES_QUIT                   40003
#define ID_BPM_90                       40004
#define ID_BPM_100                      40005
#define ID_BPM_120                      40006
#define ID_BPM_130                      40007
#define ID_BPM_140                      40008
#define ID_BPM_150                      40009
#define ID_BPM_160                      40010
#define ID_BPM_180                      40011
#define ID_FILES_MIXER                  40012
#define ID_FILES_DELAY                  40013
#define ID_FILES_GENERATETB303SOUND     40014
#define ID_HELP_ABOUT                   40015
#define ID_CUSTOM_BASE                  50000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40016
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
